import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Medical Disclaimer - RetentionHealth",
  description: "Medical disclaimer for RetentionHealth retention infrastructure platform.",
};

export default function MedicalDisclaimer() {
  return (
    <div className="bg-white py-16">
      <div className="max-w-4xl mx-auto px-6">
        <h1 className="text-4xl font-bold text-gray-900 mb-8">
          Medical Disclaimer
        </h1>
        
        <p className="text-sm text-gray-600 mb-12">
          Last Updated: March 2025
        </p>
        
        <div className="space-y-8 text-gray-700">
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              No Medical Advice
            </h2>
            <p className="mb-4">
              RetentionHealth provides behavioral reinforcement tools and operational retention analytics for healthcare programs.
            </p>
            <p className="mb-4">
              RetentionHealth does not provide medical advice, diagnosis, or treatment.
            </p>
            <p className="mb-4">
              Information generated by the platform is intended for educational and behavioral reinforcement purposes only.
            </p>
            <p className="mb-4">
              It is not a substitute for professional medical judgment.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              No Clinical Decision-Making
            </h2>
            <p className="mb-4">
              The platform:
            </p>
            <ul className="list-disc ml-6 space-y-2 mb-6">
              <li>Does not prescribe medications</li>
              <li>Does not recommend dosing changes</li>
              <li>Does not modify clinical treatment plans</li>
              <li>Does not serve as a diagnostic tool</li>
              <li>Does not replace licensed healthcare providers</li>
            </ul>
            <p className="mb-4">
              All clinical decisions remain solely the responsibility of the treating provider.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              Pilot Program Scope
            </h2>
            <p className="mb-4">
              During the 8-week pilot phase:
            </p>
            <ul className="list-disc ml-6 space-y-2 mb-6">
              <li>The system is designed to avoid handling Protected Health Information (PHI)</li>
              <li>No patient-identifiable medical records are stored</li>
              <li>The platform does not integrate with electronic medical record (EMR) systems</li>
              <li>The pilot measures operational stabilization metrics at an aggregated group level</li>
            </ul>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              Patient Responsibility
            </h2>
            <p className="mb-4">
              Patients should consult their licensed healthcare provider regarding:
            </p>
            <ul className="list-disc ml-6 space-y-2 mb-6">
              <li>Medication dosing</li>
              <li>Side effects</li>
              <li>Treatment adjustments</li>
              <li>Any medical concerns</li>
            </ul>
            <p className="mb-4">
              The RetentionHealth platform is not intended for emergency use.
            </p>
            <p className="mb-4">
              If a patient experiences a medical emergency, they should contact emergency services immediately.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              Clinic Responsibility
            </h2>
            <p className="mb-4">
              Clinic partners are solely responsible for:
            </p>
            <ul className="list-disc ml-6 space-y-2 mb-6">
              <li>Clinical supervision</li>
              <li>Regulatory compliance</li>
              <li>Obtaining patient consent</li>
              <li>Maintaining appropriate medical oversight</li>
            </ul>
            <p className="mb-4">
              RetentionHealth does not assume clinical liability.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              Contact
            </h2>
            <p className="mb-2">
              For questions regarding this disclaimer:
            </p>
            <p>
              <a 
                href="mailto:contact@retentionhealth.com?subject=Medical Disclaimer Inquiry"
                className="text-blue-600 hover:text-blue-700 font-semibold"
              >
                contact@retentionhealth.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
